
services:
  kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    volumes:
      - uptime-kuma:/app/data
      - .:/scratch
    networks:
     - pgnet

networks:
  pgnet:
    name: pg_default
    external: true

volumes:
  uptime-kuma:
